# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  fr: "Érudit"
  en: "Érudit"
subtitle:
  fr: "Rapport annuel 2015–2016"
  en: "Annual report 2015–2016"
email: info@erudit.org
description:
  fr: La mission d’Érudit est d’assurer la diffusion et la promotion des savoirs et de permettre l’accès aux corpus à des fins de recherche. Érudit favorise une diffusion ouverte.
  en: La mission d’Érudit est d’assurer la diffusion et la promotion des savoirs et de permettre l’accès aux corpus à des fins de recherche. Érudit favorise une diffusion ouverte.
index:
  fr: index.html
  en: en.html
toc:
  fr: "Table des matières"
  en: "Table of Contents"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.erudit.org/rapport/2016" # the base hostname & protocol for your site
twitter_username: eruditorg
github_username:  erudit
permalink: pretty
collections:
  - sections

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
sass:
    style: :compressed
