# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# i18n
title:
  fr: "Érudit"
  en: "Érudit"
subtitle:
  fr: "Rapport annuel 2015–2016"
  en: "Annual report 2015–2016"
tagline:
    fr: "Cultivez <br/>votre savoir."
    en: "Cultivate <br/>your knowledge."
description:
  fr: La mission d’Érudit est d’assurer la diffusion et la promotion des savoirs et de permettre l’accès aux corpus à des fins de recherche. Érudit favorise une diffusion ouverte.
  en: La mission d’Érudit est d’assurer la diffusion et la promotion des savoirs et de permettre l’accès aux corpus à des fins de recherche. Érudit favorise une diffusion ouverte.
index:
  fr: index.html
  en: en.html
toc:
  fr: "Table des matières"
  en: "Table of Contents"
share:
  fr: "Partager"
  en: "Share"
cover_page:
  fr: "Page couverture"
  en: "First page"
about:
  fr: "À propos d’Érudit"
  en: "About Érudit"
about_url:
  fr: "https://apropos.erudit.org/fr/"
  en: "https://apropos.erudit.org/en/"
newsletter:
  fr: "Inscrivez-vous à notre infolettre"
  en: "Subscribe to our newsletter"
newsletter_url:
  fr: "//erudit.us3.list-manage.com/subscribe/post?u=b865f2a1d7079a1246f02d4c5&amp;id=baa73f54fd"
  en: "//erudit.us3.list-manage.com/subscribe/post?u=b865f2a1d7079a1246f02d4c5&amp;id=baa73f54fd"
subscribe:
  fr: "S’inscrire"
  en: "Subscribe"

# Social media + contact
email: info@erudit.org
twitter_username: eruditorg
github_username:  erudit
facebook_username: erudit.org

# Site settings
url: "https://www.erudit.org/rapport/2016"
permalink: pretty
collections:
  - sections

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
sass:
    style: :compressed
